
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG2vuqF7gQkwvywNy3AzDC4YqYB7QKcRY',
    authDomain: 'praktikum-mobileapp-57350.firebaseapp.com',
    databaseURL: 'https://praktikum-mobileapp-57350-default-rtdb.asia-southeast1.firebasedatabase.app',
    projectId: 'praktikum-mobileapp-57350',
    storageBucket: 'praktikum-mobileapp-57350.appspot.com',
    messagingSenderId: '501315397279',
    appId: '1:501315397279:web:20f4cad50e8b516f5464aa'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLZ4FA5c-hnzt3ealjESXdHLnh0ivDerw',
    appId: '1:501315397279:android:210cfce38e9629fb5464aa',
    messagingSenderId: '501315397279',
    projectId: 'praktikum-mobileapp-57350',
    storageBucket: 'praktikum-mobileapp-57350.appspot.com'
  );
}
